FROM node:22-alpine
WORKDIR /app
RUN addgroup -g 1001 -S nodejs && adduser -S nodejs -u 1001 -G nodejs
COPY package*.json ./
RUN npm install && chown -R nodejs:nodejs /app
USER nodejs
COPY --chown=nodejs:nodejs . .
EXPOSE 3000
CMD ["npm", "run", "dev"]
